# Generated by Django 5.1.1 on 2024-10-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctorings', '0006_proctoringlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoringlog',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
