# Generated by Django 5.1.1 on 2024-10-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctorings', '0007_alter_proctoringlog_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoringlog',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
